require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FavoritetweetsController do

  def mock_favoritetweet(stubs={})
    @mock_favoritetweet ||= mock_model(Favoritetweet, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all favoritetweets as @favoritetweets" do
      Favoritetweet.stub(:all) { [mock_favoritetweet] }
      get :index
      assigns(:favoritetweets).should eq([mock_favoritetweet])
    end
  end

  describe "GET show" do
    it "assigns the requested favoritetweet as @favoritetweet" do
      Favoritetweet.stub(:find).with("37") { mock_favoritetweet }
      get :show, :id => "37"
      assigns(:favoritetweet).should be(mock_favoritetweet)
    end
  end

  describe "GET new" do
    it "assigns a new favoritetweet as @favoritetweet" do
      Favoritetweet.stub(:new) { mock_favoritetweet }
      get :new
      assigns(:favoritetweet).should be(mock_favoritetweet)
    end
  end

  describe "GET edit" do
    it "assigns the requested favoritetweet as @favoritetweet" do
      Favoritetweet.stub(:find).with("37") { mock_favoritetweet }
      get :edit, :id => "37"
      assigns(:favoritetweet).should be(mock_favoritetweet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created favoritetweet as @favoritetweet" do
        Favoritetweet.stub(:new).with({'these' => 'params'}) { mock_favoritetweet(:save => true) }
        post :create, :favoritetweet => {'these' => 'params'}
        assigns(:favoritetweet).should be(mock_favoritetweet)
      end

      it "redirects to the created favoritetweet" do
        Favoritetweet.stub(:new) { mock_favoritetweet(:save => true) }
        post :create, :favoritetweet => {}
        response.should redirect_to(favoritetweet_url(mock_favoritetweet))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved favoritetweet as @favoritetweet" do
        Favoritetweet.stub(:new).with({'these' => 'params'}) { mock_favoritetweet(:save => false) }
        post :create, :favoritetweet => {'these' => 'params'}
        assigns(:favoritetweet).should be(mock_favoritetweet)
      end

      it "re-renders the 'new' template" do
        Favoritetweet.stub(:new) { mock_favoritetweet(:save => false) }
        post :create, :favoritetweet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested favoritetweet" do
        Favoritetweet.stub(:find).with("37") { mock_favoritetweet }
        mock_favoritetweet.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :favoritetweet => {'these' => 'params'}
      end

      it "assigns the requested favoritetweet as @favoritetweet" do
        Favoritetweet.stub(:find) { mock_favoritetweet(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:favoritetweet).should be(mock_favoritetweet)
      end

      it "redirects to the favoritetweet" do
        Favoritetweet.stub(:find) { mock_favoritetweet(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(favoritetweet_url(mock_favoritetweet))
      end
    end

    describe "with invalid params" do
      it "assigns the favoritetweet as @favoritetweet" do
        Favoritetweet.stub(:find) { mock_favoritetweet(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:favoritetweet).should be(mock_favoritetweet)
      end

      it "re-renders the 'edit' template" do
        Favoritetweet.stub(:find) { mock_favoritetweet(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested favoritetweet" do
      Favoritetweet.stub(:find).with("37") { mock_favoritetweet }
      mock_favoritetweet.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the favoritetweets list" do
      Favoritetweet.stub(:find) { mock_favoritetweet }
      delete :destroy, :id => "1"
      response.should redirect_to(favoritetweets_url)
    end
  end

end
