require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FollowsusersController do

  def mock_followsuser(stubs={})
    @mock_followsuser ||= mock_model(Followsuser, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all followsusers as @followsusers" do
      Followsuser.stub(:all) { [mock_followsuser] }
      get :index
      assigns(:followsusers).should eq([mock_followsuser])
    end
  end

  describe "GET show" do
    it "assigns the requested followsuser as @followsuser" do
      Followsuser.stub(:find).with("37") { mock_followsuser }
      get :show, :id => "37"
      assigns(:followsuser).should be(mock_followsuser)
    end
  end

  describe "GET new" do
    it "assigns a new followsuser as @followsuser" do
      Followsuser.stub(:new) { mock_followsuser }
      get :new
      assigns(:followsuser).should be(mock_followsuser)
    end
  end

  describe "GET edit" do
    it "assigns the requested followsuser as @followsuser" do
      Followsuser.stub(:find).with("37") { mock_followsuser }
      get :edit, :id => "37"
      assigns(:followsuser).should be(mock_followsuser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created followsuser as @followsuser" do
        Followsuser.stub(:new).with({'these' => 'params'}) { mock_followsuser(:save => true) }
        post :create, :followsuser => {'these' => 'params'}
        assigns(:followsuser).should be(mock_followsuser)
      end

      it "redirects to the created followsuser" do
        Followsuser.stub(:new) { mock_followsuser(:save => true) }
        post :create, :followsuser => {}
        response.should redirect_to(followsuser_url(mock_followsuser))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved followsuser as @followsuser" do
        Followsuser.stub(:new).with({'these' => 'params'}) { mock_followsuser(:save => false) }
        post :create, :followsuser => {'these' => 'params'}
        assigns(:followsuser).should be(mock_followsuser)
      end

      it "re-renders the 'new' template" do
        Followsuser.stub(:new) { mock_followsuser(:save => false) }
        post :create, :followsuser => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested followsuser" do
        Followsuser.stub(:find).with("37") { mock_followsuser }
        mock_followsuser.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :followsuser => {'these' => 'params'}
      end

      it "assigns the requested followsuser as @followsuser" do
        Followsuser.stub(:find) { mock_followsuser(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:followsuser).should be(mock_followsuser)
      end

      it "redirects to the followsuser" do
        Followsuser.stub(:find) { mock_followsuser(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(followsuser_url(mock_followsuser))
      end
    end

    describe "with invalid params" do
      it "assigns the followsuser as @followsuser" do
        Followsuser.stub(:find) { mock_followsuser(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:followsuser).should be(mock_followsuser)
      end

      it "re-renders the 'edit' template" do
        Followsuser.stub(:find) { mock_followsuser(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested followsuser" do
      Followsuser.stub(:find).with("37") { mock_followsuser }
      mock_followsuser.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the followsusers list" do
      Followsuser.stub(:find) { mock_followsuser }
      delete :destroy, :id => "1"
      response.should redirect_to(followsusers_url)
    end
  end

end
