require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FollowslistsController do

  def mock_followslist(stubs={})
    @mock_followslist ||= mock_model(Followslist, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all followslists as @followslists" do
      Followslist.stub(:all) { [mock_followslist] }
      get :index
      assigns(:followslists).should eq([mock_followslist])
    end
  end

  describe "GET show" do
    it "assigns the requested followslist as @followslist" do
      Followslist.stub(:find).with("37") { mock_followslist }
      get :show, :id => "37"
      assigns(:followslist).should be(mock_followslist)
    end
  end

  describe "GET new" do
    it "assigns a new followslist as @followslist" do
      Followslist.stub(:new) { mock_followslist }
      get :new
      assigns(:followslist).should be(mock_followslist)
    end
  end

  describe "GET edit" do
    it "assigns the requested followslist as @followslist" do
      Followslist.stub(:find).with("37") { mock_followslist }
      get :edit, :id => "37"
      assigns(:followslist).should be(mock_followslist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created followslist as @followslist" do
        Followslist.stub(:new).with({'these' => 'params'}) { mock_followslist(:save => true) }
        post :create, :followslist => {'these' => 'params'}
        assigns(:followslist).should be(mock_followslist)
      end

      it "redirects to the created followslist" do
        Followslist.stub(:new) { mock_followslist(:save => true) }
        post :create, :followslist => {}
        response.should redirect_to(followslist_url(mock_followslist))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved followslist as @followslist" do
        Followslist.stub(:new).with({'these' => 'params'}) { mock_followslist(:save => false) }
        post :create, :followslist => {'these' => 'params'}
        assigns(:followslist).should be(mock_followslist)
      end

      it "re-renders the 'new' template" do
        Followslist.stub(:new) { mock_followslist(:save => false) }
        post :create, :followslist => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested followslist" do
        Followslist.stub(:find).with("37") { mock_followslist }
        mock_followslist.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :followslist => {'these' => 'params'}
      end

      it "assigns the requested followslist as @followslist" do
        Followslist.stub(:find) { mock_followslist(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:followslist).should be(mock_followslist)
      end

      it "redirects to the followslist" do
        Followslist.stub(:find) { mock_followslist(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(followslist_url(mock_followslist))
      end
    end

    describe "with invalid params" do
      it "assigns the followslist as @followslist" do
        Followslist.stub(:find) { mock_followslist(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:followslist).should be(mock_followslist)
      end

      it "re-renders the 'edit' template" do
        Followslist.stub(:find) { mock_followslist(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested followslist" do
      Followslist.stub(:find).with("37") { mock_followslist }
      mock_followslist.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the followslists list" do
      Followslist.stub(:find) { mock_followslist }
      delete :destroy, :id => "1"
      response.should redirect_to(followslists_url)
    end
  end

end
