require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe InlistsController do

  def mock_inlist(stubs={})
    @mock_inlist ||= mock_model(Inlist, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all inlists as @inlists" do
      Inlist.stub(:all) { [mock_inlist] }
      get :index
      assigns(:inlists).should eq([mock_inlist])
    end
  end

  describe "GET show" do
    it "assigns the requested inlist as @inlist" do
      Inlist.stub(:find).with("37") { mock_inlist }
      get :show, :id => "37"
      assigns(:inlist).should be(mock_inlist)
    end
  end

  describe "GET new" do
    it "assigns a new inlist as @inlist" do
      Inlist.stub(:new) { mock_inlist }
      get :new
      assigns(:inlist).should be(mock_inlist)
    end
  end

  describe "GET edit" do
    it "assigns the requested inlist as @inlist" do
      Inlist.stub(:find).with("37") { mock_inlist }
      get :edit, :id => "37"
      assigns(:inlist).should be(mock_inlist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created inlist as @inlist" do
        Inlist.stub(:new).with({'these' => 'params'}) { mock_inlist(:save => true) }
        post :create, :inlist => {'these' => 'params'}
        assigns(:inlist).should be(mock_inlist)
      end

      it "redirects to the created inlist" do
        Inlist.stub(:new) { mock_inlist(:save => true) }
        post :create, :inlist => {}
        response.should redirect_to(inlist_url(mock_inlist))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inlist as @inlist" do
        Inlist.stub(:new).with({'these' => 'params'}) { mock_inlist(:save => false) }
        post :create, :inlist => {'these' => 'params'}
        assigns(:inlist).should be(mock_inlist)
      end

      it "re-renders the 'new' template" do
        Inlist.stub(:new) { mock_inlist(:save => false) }
        post :create, :inlist => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inlist" do
        Inlist.stub(:find).with("37") { mock_inlist }
        mock_inlist.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :inlist => {'these' => 'params'}
      end

      it "assigns the requested inlist as @inlist" do
        Inlist.stub(:find) { mock_inlist(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:inlist).should be(mock_inlist)
      end

      it "redirects to the inlist" do
        Inlist.stub(:find) { mock_inlist(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(inlist_url(mock_inlist))
      end
    end

    describe "with invalid params" do
      it "assigns the inlist as @inlist" do
        Inlist.stub(:find) { mock_inlist(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:inlist).should be(mock_inlist)
      end

      it "re-renders the 'edit' template" do
        Inlist.stub(:find) { mock_inlist(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inlist" do
      Inlist.stub(:find).with("37") { mock_inlist }
      mock_inlist.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the inlists list" do
      Inlist.stub(:find) { mock_inlist }
      delete :destroy, :id => "1"
      response.should redirect_to(inlists_url)
    end
  end

end
