require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MentionsController do

  def mock_mention(stubs={})
    @mock_mention ||= mock_model(Mention, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all mentions as @mentions" do
      Mention.stub(:all) { [mock_mention] }
      get :index
      assigns(:mentions).should eq([mock_mention])
    end
  end

  describe "GET show" do
    it "assigns the requested mention as @mention" do
      Mention.stub(:find).with("37") { mock_mention }
      get :show, :id => "37"
      assigns(:mention).should be(mock_mention)
    end
  end

  describe "GET new" do
    it "assigns a new mention as @mention" do
      Mention.stub(:new) { mock_mention }
      get :new
      assigns(:mention).should be(mock_mention)
    end
  end

  describe "GET edit" do
    it "assigns the requested mention as @mention" do
      Mention.stub(:find).with("37") { mock_mention }
      get :edit, :id => "37"
      assigns(:mention).should be(mock_mention)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created mention as @mention" do
        Mention.stub(:new).with({'these' => 'params'}) { mock_mention(:save => true) }
        post :create, :mention => {'these' => 'params'}
        assigns(:mention).should be(mock_mention)
      end

      it "redirects to the created mention" do
        Mention.stub(:new) { mock_mention(:save => true) }
        post :create, :mention => {}
        response.should redirect_to(mention_url(mock_mention))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mention as @mention" do
        Mention.stub(:new).with({'these' => 'params'}) { mock_mention(:save => false) }
        post :create, :mention => {'these' => 'params'}
        assigns(:mention).should be(mock_mention)
      end

      it "re-renders the 'new' template" do
        Mention.stub(:new) { mock_mention(:save => false) }
        post :create, :mention => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mention" do
        Mention.stub(:find).with("37") { mock_mention }
        mock_mention.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :mention => {'these' => 'params'}
      end

      it "assigns the requested mention as @mention" do
        Mention.stub(:find) { mock_mention(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:mention).should be(mock_mention)
      end

      it "redirects to the mention" do
        Mention.stub(:find) { mock_mention(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(mention_url(mock_mention))
      end
    end

    describe "with invalid params" do
      it "assigns the mention as @mention" do
        Mention.stub(:find) { mock_mention(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:mention).should be(mock_mention)
      end

      it "re-renders the 'edit' template" do
        Mention.stub(:find) { mock_mention(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mention" do
      Mention.stub(:find).with("37") { mock_mention }
      mock_mention.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the mentions list" do
      Mention.stub(:find) { mock_mention }
      delete :destroy, :id => "1"
      response.should redirect_to(mentions_url)
    end
  end

end
