require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MessagerelationsController do

  def mock_messagerelation(stubs={})
    @mock_messagerelation ||= mock_model(Messagerelation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all messagerelations as @messagerelations" do
      Messagerelation.stub(:all) { [mock_messagerelation] }
      get :index
      assigns(:messagerelations).should eq([mock_messagerelation])
    end
  end

  describe "GET show" do
    it "assigns the requested messagerelation as @messagerelation" do
      Messagerelation.stub(:find).with("37") { mock_messagerelation }
      get :show, :id => "37"
      assigns(:messagerelation).should be(mock_messagerelation)
    end
  end

  describe "GET new" do
    it "assigns a new messagerelation as @messagerelation" do
      Messagerelation.stub(:new) { mock_messagerelation }
      get :new
      assigns(:messagerelation).should be(mock_messagerelation)
    end
  end

  describe "GET edit" do
    it "assigns the requested messagerelation as @messagerelation" do
      Messagerelation.stub(:find).with("37") { mock_messagerelation }
      get :edit, :id => "37"
      assigns(:messagerelation).should be(mock_messagerelation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created messagerelation as @messagerelation" do
        Messagerelation.stub(:new).with({'these' => 'params'}) { mock_messagerelation(:save => true) }
        post :create, :messagerelation => {'these' => 'params'}
        assigns(:messagerelation).should be(mock_messagerelation)
      end

      it "redirects to the created messagerelation" do
        Messagerelation.stub(:new) { mock_messagerelation(:save => true) }
        post :create, :messagerelation => {}
        response.should redirect_to(messagerelation_url(mock_messagerelation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved messagerelation as @messagerelation" do
        Messagerelation.stub(:new).with({'these' => 'params'}) { mock_messagerelation(:save => false) }
        post :create, :messagerelation => {'these' => 'params'}
        assigns(:messagerelation).should be(mock_messagerelation)
      end

      it "re-renders the 'new' template" do
        Messagerelation.stub(:new) { mock_messagerelation(:save => false) }
        post :create, :messagerelation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested messagerelation" do
        Messagerelation.stub(:find).with("37") { mock_messagerelation }
        mock_messagerelation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :messagerelation => {'these' => 'params'}
      end

      it "assigns the requested messagerelation as @messagerelation" do
        Messagerelation.stub(:find) { mock_messagerelation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:messagerelation).should be(mock_messagerelation)
      end

      it "redirects to the messagerelation" do
        Messagerelation.stub(:find) { mock_messagerelation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(messagerelation_url(mock_messagerelation))
      end
    end

    describe "with invalid params" do
      it "assigns the messagerelation as @messagerelation" do
        Messagerelation.stub(:find) { mock_messagerelation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:messagerelation).should be(mock_messagerelation)
      end

      it "re-renders the 'edit' template" do
        Messagerelation.stub(:find) { mock_messagerelation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested messagerelation" do
      Messagerelation.stub(:find).with("37") { mock_messagerelation }
      mock_messagerelation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the messagerelations list" do
      Messagerelation.stub(:find) { mock_messagerelation }
      delete :destroy, :id => "1"
      response.should redirect_to(messagerelations_url)
    end
  end

end
