require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TagmentionsController do

  def mock_tagmention(stubs={})
    @mock_tagmention ||= mock_model(Tagmention, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tagmentions as @tagmentions" do
      Tagmention.stub(:all) { [mock_tagmention] }
      get :index
      assigns(:tagmentions).should eq([mock_tagmention])
    end
  end

  describe "GET show" do
    it "assigns the requested tagmention as @tagmention" do
      Tagmention.stub(:find).with("37") { mock_tagmention }
      get :show, :id => "37"
      assigns(:tagmention).should be(mock_tagmention)
    end
  end

  describe "GET new" do
    it "assigns a new tagmention as @tagmention" do
      Tagmention.stub(:new) { mock_tagmention }
      get :new
      assigns(:tagmention).should be(mock_tagmention)
    end
  end

  describe "GET edit" do
    it "assigns the requested tagmention as @tagmention" do
      Tagmention.stub(:find).with("37") { mock_tagmention }
      get :edit, :id => "37"
      assigns(:tagmention).should be(mock_tagmention)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tagmention as @tagmention" do
        Tagmention.stub(:new).with({'these' => 'params'}) { mock_tagmention(:save => true) }
        post :create, :tagmention => {'these' => 'params'}
        assigns(:tagmention).should be(mock_tagmention)
      end

      it "redirects to the created tagmention" do
        Tagmention.stub(:new) { mock_tagmention(:save => true) }
        post :create, :tagmention => {}
        response.should redirect_to(tagmention_url(mock_tagmention))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tagmention as @tagmention" do
        Tagmention.stub(:new).with({'these' => 'params'}) { mock_tagmention(:save => false) }
        post :create, :tagmention => {'these' => 'params'}
        assigns(:tagmention).should be(mock_tagmention)
      end

      it "re-renders the 'new' template" do
        Tagmention.stub(:new) { mock_tagmention(:save => false) }
        post :create, :tagmention => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tagmention" do
        Tagmention.stub(:find).with("37") { mock_tagmention }
        mock_tagmention.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tagmention => {'these' => 'params'}
      end

      it "assigns the requested tagmention as @tagmention" do
        Tagmention.stub(:find) { mock_tagmention(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tagmention).should be(mock_tagmention)
      end

      it "redirects to the tagmention" do
        Tagmention.stub(:find) { mock_tagmention(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(tagmention_url(mock_tagmention))
      end
    end

    describe "with invalid params" do
      it "assigns the tagmention as @tagmention" do
        Tagmention.stub(:find) { mock_tagmention(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tagmention).should be(mock_tagmention)
      end

      it "re-renders the 'edit' template" do
        Tagmention.stub(:find) { mock_tagmention(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tagmention" do
      Tagmention.stub(:find).with("37") { mock_tagmention }
      mock_tagmention.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tagmentions list" do
      Tagmention.stub(:find) { mock_tagmention }
      delete :destroy, :id => "1"
      response.should redirect_to(tagmentions_url)
    end
  end

end
